### PR TITLE
incorporate ompMC into matRad

### PR DESCRIPTION
**Pull request by markbangert**

### CODE REVIEW

**Comment by markbangert** [comment]
@edoerner please use this branch as reference for all future developments...

**Comment by edoerner** [comment]
Ok, @markbangert . Here is an image of a first implementation of the beamlet source (example4, Gantry angles 0, 90). I will create a pull request for that. It needs of course further testing, but it is a first approach :)

screen shot 2018-12-20 at 5 46 11 pm

**Comment by markbangert** [comment]
That looks really cool! I will review as soon as possible so we can merge...

**Comment by markbangert** [comment]
@edoerner: look at this

image

I can reproduce your results. As we are working with identical random seeds, the dose pattern looks exactly identical :)

**Comment by markbangert** [comment]
Obsolete. All development now in https://github.com/e0404/matRad/tree/dev_ompMC.

**Pull request closed without merging**
