### PR TITLE
removed redundant parenthesis and applied CompFac also to L_Bro

### PR DESCRIPTION
**Pull request by johannawinter**

### CODE REVIEW

**Comment by markbangert** [comment]
Nice work @johannawinter! Just to clarify... did you consult with @becker89 and run a couple of tests to verify?

**Comment by johannawinter** [comment]
I did consult @becker89 before. Forgot to run tests at first but did it now (with matRadGUI). Seems to work fine although I don't know how the bug with the CompFac showed up before.

**Comment by markbangert** [comment]
alright. will merge now into the dev branch and during the hackfest we are going to perform a detailed evaluation!

**Comment by becker89** [comment]
It would be helpful to test if the integral dose of a certain pencil beam stays approximately the same when (i) applying and (ii) neglecting a lateral cutoff.

**Pull request merged**
