### PR TITLE
make option to select dicom file based on series number available again

### PR DESCRIPTION
**Pull request by markbangert**
For some reason it was not possible to enable DICOM file sorting according to the SeriesNumber by pressing the radio button. This pull request is supposed to fix this.

@becker89: Please wait with merging. I need to reconfirm with the colleagues in Madrid who submitted this issue via email if this completely fixes their problem. I am afraid there is some more work to do with regard to dicom plan and dose!

@hubertgabrys: thank you for the pointer towards the series number. I would appreciate if you could also keep an eye on this pull request as dicom expert.

### CODE REVIEW

**Comment by markbangert** [comment]
@hubertgabrys would you have a minute to review this today or tomorrow?

**Comment by hubertgabrys** [comment]
Will do.

**Comment by markbangert** [comment]
Thank you very much for your input. I just pushed a couple of changes that should settle all your comments plus some more modifications. I would be very happy of you could revise once more...

**Comment by markbangert** [comment]
@hubertgabrys can I perform the merge or are there still things open?

**Comment by hubertgabrys** [comment]
RT Structure Set listbox displays SeriesInstanceUID not SOPInstanceUID. We should add: 
```
case 'RTSTRUCT'
   try
      fileList{i,4} = info.SOPInstanceUID;
   catch
      fileList{i,4} = NaN;
   end
```
 in https://github.com/e0404/matRad/blob/master/dicomImport/matRad_scanDicomImportFolder.m#L90

Apart from that it seems all good.

**Comment by markbangert** [comment]
thank you @hubertgabrys for your thorough review! I made the changes in https://github.com/e0404/matRad/pull/229/commits/1b62a89f5ebc917d6b79c310be9f3f0fe95235c3 and will merge now!

**Pull request merged**
