### PR TITLE
Bugfix color contours and legend matching

### PR DESCRIPTION
**Pull request by Haydnspass**
Colours now stored in cst{i,5}.visibleColor.
@wahln: One can just change one line in setCstTable and go for another than the usual colorcube. Is that okay or would u prefer it differntly?

### CODE REVIEW

**Comment by wahln** [comment]
I would prefer to still have the cMap option as optional argument in matRad_plotVoiContoursSlice (and if it is passed the function will use the colormap colors), since then you can just call the function from a custom script without changing code in the matRad files, which one might forget to change back etc

**Comment by Haydnspass** [comment]
Okay I see and agree. I will change it.

**Comment by markbangert** [comment]
Great. Let me know when you are ready. Then I will review and merge.

Cheers.

Am 17.02.2017 6:33 nachm. schrieb "Lucas" <notifications@github.com>:

**Comment by Haydnspass** [comment]
@wahln : you meant only the contour slices or the legendTable as well? For the former it's done.

**Comment by markbangert** [comment]
This is still buggy. To reproduce the bug you can:

1. Open the th GUI with blank workspace
2. load some mat data set
3. toggle on/off some structures
4. load the next mat data set
5. toggle on/off -> does not work

**Comment by Haydnspass** [comment]
Okay this was odd. This bug should be fixed now.

**Pull request merged**
