### PR TITLE
Possible bug in TOPAS engine with dij calculation

### PR DESCRIPTION
**Pull request by remocristoforetti**
strjoint requires a string not a char array. This is a possible fix, I only tested in one specific case, but it's a small fix.

### CODE REVIEW

**Comment by wahln** [comment]
Can you explain the issue?

A problem of this proposed fix is that "string" does not exist in Octave. We need to work with char arrays.

**Comment by remocristoforetti** [comment]
Ah I see, the error is triggered by `strjoin` at line 2078. Possibly the char array `imageName` is not accepted as a valid input.
Avoiding the use of `strjoin` seams to work as well

**Comment by wahln** [comment]
But `strjoin({'test','test2'},';')` works without issues on cell arrays of chars, so I still don't get it.

**Comment by wahln** [comment]
Ah I guess that imageName already is a joined char array, so we don't need strjoin.

**Pull request closed without merging**
